version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    env_file:
      - .env.production
    ports:
      - 80:80
    container_name: mern-api
    networks:
      - mern-stack-net

networks:
  mern-stack-net:
    driver: bridge