version: "3"
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    env_file:
      - .env.prod
    environment:
      - PORT
    ports:
      -  3000:3000
    container_name: mern-ui
    networks:
      -  mern-stack-net
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    env_file:
      - .env.prod
    ports:
      - 80:80
    container_name: mern-api
    networks:
      - mern-stack-net

networks:
  mern-stack-net:
    driver: bridge