# Pull the Node image from Docker Hub
FROM node:16

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

# Pass down port from env
ENV PORT=${PORT}
ENV ENVIRONMENT=${ENVIRONMENT}
ENV BASE_URL=${BASE_URL}

EXPOSE 3000

# Run the React app
CMD ["npm", "start"]