# Pull the Node image from Docker Hub
FROM node:16

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

ENV ENVIRONMENT=${ENVIRONMENT}
ENV PORT=${PORT}
ENV DATABASE_URL=${DATABASE_URL}

EXPOSE ${PORT}

# Run the API on Nodemon
CMD ["npm", "run", "start:nodemon"]